name: networks
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - intel-openmp=2022.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - liblapack=3.9.0
  - libzlib=1.2.11
  - mkl=2021.4.0
  - numpy=1.21.5
  - openssl=3.0.0
  - pandas=1.3.5
  - pip=21.3.1
  - python=3.10.1
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2021.3
  - setuptools=60.1.1
  - six=1.16.0
  - sqlite=3.37.0
  - tbb=2021.5.0
  - tk=8.6.11
  - tzdata=2021e
  - ucrt=10.0.20348.0
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wheel=0.37.1
  - xz=5.2.5
  - pip:
    - networkx==2.6.3
