name: netx
channels:
  - conda-forge
  - defaults
dependencies:
  - backcall=0.2.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - colorama=0.4.4
  - debugpy=1.5.1
  - decorator=5.1.0
  - entrypoints=0.3
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jupyter_client=7.1.0
  - jupyter_core=4.9.1
  - matplotlib-inline=0.1.2
  - nest-asyncio=1.5.1
  - openssl=1.1.1l
  - parso=0.8.2
  - pickleshare=0.7.5
  - pip=21.2.4
  - prompt-toolkit=3.0.20
  - pygments=2.10.0
  - python=3.9.7
  - python-dateutil=2.8.2
  - pywin32=302
  - pyzmq=22.3.0
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.0
  - tornado=6.1
  - traitlets=5.1.1
  - tzdata=2021e
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.37.0
  - wincertstore=0.2
  - pip:
    - cycler==0.11.0
    - fonttools==4.28.5
    - kiwisolver==1.3.2
    - matplotlib==3.5.1
    - networkx==2.6.3
    - numpy==1.22.0
    - packaging==21.3
    - pandas==1.3.5
    - pillow==9.0.0
    - pyparsing==3.0.6
    - pytz==2021.3
    - scipy==1.7.3
